project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Daily Rhythms of Stress"
  subtitle: "A Wearable-Based Exploration of Physiology and Behavior"
  author: "Yan Li (yl6037)"
  date: today

  search: true

  repo-url: https://github.com/yanzzzk/edav-final-project
  repo-actions: [edit, source]

  sidebar:
    style: docked
    background: light
    collapse-level: 1

  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

  page-footer:
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>
    left: |
      &copy; 2023 Yan Li (EDAV Final Project)

format:
  html:
    theme: cosmo

    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "On this page"

    code-fold: true
    code-summary: "Show Code"
    code-tools: true
    code-copy: true
    code-line-numbers: true

    number-sections: true

    smooth-scroll: true

    link-external-icon: true
    link-external-newwindow: true
